version: "4"

services:
    mysql:
        image: mysql:8.3.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    redis:
        image: redis:7.2.4
        container_name: redis
        restart: always
        ports:
            - "6379:6379"